# Generated by Django 4.2.4 on 2024-02-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_json', models.CharField(max_length=5000)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=50)),
                ('add1', models.CharField(max_length=500)),
                ('add2', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=8)),
            ],
        ),
    ]
