# Generated by Django 4.2.4 on 2024-02-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
